USE [master]
GO
/****** Object:  Database [GraphQL_DB]    Script Date: 9/20/2021 1:14:45 AM ******/
CREATE DATABASE [GraphQL_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GraphQL_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GraphQL_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GraphQL_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GraphQL_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GraphQL_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GraphQL_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GraphQL_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GraphQL_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GraphQL_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GraphQL_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GraphQL_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [GraphQL_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GraphQL_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GraphQL_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GraphQL_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GraphQL_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GraphQL_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GraphQL_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GraphQL_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GraphQL_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GraphQL_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GraphQL_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GraphQL_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GraphQL_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GraphQL_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GraphQL_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GraphQL_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GraphQL_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GraphQL_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [GraphQL_DB] SET  MULTI_USER 
GO
ALTER DATABASE [GraphQL_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GraphQL_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GraphQL_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GraphQL_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GraphQL_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GraphQL_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GraphQL_DB', N'ON'
GO
ALTER DATABASE [GraphQL_DB] SET QUERY_STORE = OFF
GO
USE [GraphQL_DB]
GO
/****** Object:  Table [dbo].[CountryRecords]    Script Date: 9/20/2021 1:14:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CountryRecords](
	[CountryId] [int] IDENTITY(1,1) NOT NULL,
	[Country] [nvarchar](max) NOT NULL,
	[Year] [nvarchar](max) NOT NULL,
	[Area] [bigint] NOT NULL,
	[TotalPopulation] [bigint] NOT NULL,
 CONSTRAINT [PK_CountryRecords] PRIMARY KEY CLUSTERED 
(
	[CountryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [GraphQL_DB] SET  READ_WRITE 
GO
